ARG BASE=mtangemann/deeplearning-base:v1-ubuntu18.04-cuda11.1-python3.8
FROM $BASE

RUN pip install \
    click==7.1.2 \
    executor==23.2 \
    imageio==2.9.0 \
    jupyterlab==3.0.12 \
    matplotlib==3.4.1 \
    numpy==1.20.2 \
    pandas==1.2.3 \
    scipy==1.6.2 \
    scikit-learn==0.24.1 \
    seaborn==0.11.1 \
    torch==1.8.1 \
    torchvision==0.9.1
